// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Boundary
{
    public static class GetAuthMethod
    {
        public static Task<GetAuthMethodResult> InvokeAsync(GetAuthMethodArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAuthMethodResult>("boundary:index/getAuthMethod:getAuthMethod", args ?? new GetAuthMethodArgs(), options.WithDefaults());

        public static Output<GetAuthMethodResult> Invoke(GetAuthMethodInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAuthMethodResult>("boundary:index/getAuthMethod:getAuthMethod", args ?? new GetAuthMethodInvokeArgs(), options.WithDefaults());

        public static Output<GetAuthMethodResult> Invoke(GetAuthMethodInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAuthMethodResult>("boundary:index/getAuthMethod:getAuthMethod", args ?? new GetAuthMethodInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAuthMethodArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("scopeId")]
        public string? ScopeId { get; set; }

        public GetAuthMethodArgs()
        {
        }
        public static new GetAuthMethodArgs Empty => new GetAuthMethodArgs();
    }

    public sealed class GetAuthMethodInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("scopeId")]
        public Input<string>? ScopeId { get; set; }

        public GetAuthMethodInvokeArgs()
        {
        }
        public static new GetAuthMethodInvokeArgs Empty => new GetAuthMethodInvokeArgs();
    }


    [OutputType]
    public sealed class GetAuthMethodResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;
        public readonly string? ScopeId;
        public readonly ImmutableArray<Outputs.GetAuthMethodScopeResult> Scopes;
        public readonly string Type;

        [OutputConstructor]
        private GetAuthMethodResult(
            string description,

            string id,

            string name,

            string? scopeId,

            ImmutableArray<Outputs.GetAuthMethodScopeResult> scopes,

            string type)
        {
            Description = description;
            Id = id;
            Name = name;
            ScopeId = scopeId;
            Scopes = scopes;
            Type = type;
        }
    }
}
