// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Boundary
{
    /// <summary>
    /// The static host resource allows you to configure a Boundary static host. Hosts are always part of a project, so a project resource should be used inline or you should have the project ID in hand to successfully configure a host.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Boundary = Pulumi.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.Scope("org", new()
    ///     {
    ///         Name = "organization_one",
    ///         Description = "My first scope!",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var project = new Boundary.Scope("project", new()
    ///     {
    ///         Name = "project_one",
    ///         Description = "My first scope!",
    ///         ScopeId = org.Id,
    ///         AutoCreateAdminRole = true,
    ///     });
    /// 
    ///     var example = new Boundary.HostCatalogStatic("example", new()
    ///     {
    ///         Name = "My catalog",
    ///         Description = "My first host catalog!",
    ///         ScopeId = project.Id,
    ///     });
    /// 
    ///     var exampleHostStatic = new Boundary.HostStatic("example", new()
    ///     {
    ///         Name = "example_host",
    ///         Description = "My first host!",
    ///         Address = "10.0.0.1",
    ///         HostCatalogId = example.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import boundary:index/hostStatic:HostStatic foo &lt;my-id&gt;
    /// ```
    /// </summary>
    [BoundaryResourceType("boundary:index/hostStatic:HostStatic")]
    public partial class HostStatic : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The static address of the host resource as `&lt;IP&gt;` (note: port assignment occurs in the target resource definition, do not add :port here) or a domain name.
        /// </summary>
        [Output("address")]
        public Output<string?> Address { get; private set; } = null!;

        /// <summary>
        /// The host description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("hostCatalogId")]
        public Output<string> HostCatalogId { get; private set; } = null!;

        /// <summary>
        /// The host name. Defaults to the resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The type of host
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;


        /// <summary>
        /// Create a HostStatic resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public HostStatic(string name, HostStaticArgs args, CustomResourceOptions? options = null)
            : base("boundary:index/hostStatic:HostStatic", name, args ?? new HostStaticArgs(), MakeResourceOptions(options, ""))
        {
        }

        private HostStatic(string name, Input<string> id, HostStaticState? state = null, CustomResourceOptions? options = null)
            : base("boundary:index/hostStatic:HostStatic", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing HostStatic resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static HostStatic Get(string name, Input<string> id, HostStaticState? state = null, CustomResourceOptions? options = null)
        {
            return new HostStatic(name, id, state, options);
        }
    }

    public sealed class HostStaticArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The static address of the host resource as `&lt;IP&gt;` (note: port assignment occurs in the target resource definition, do not add :port here) or a domain name.
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// The host description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("hostCatalogId", required: true)]
        public Input<string> HostCatalogId { get; set; } = null!;

        /// <summary>
        /// The host name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The type of host
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public HostStaticArgs()
        {
        }
        public static new HostStaticArgs Empty => new HostStaticArgs();
    }

    public sealed class HostStaticState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The static address of the host resource as `&lt;IP&gt;` (note: port assignment occurs in the target resource definition, do not add :port here) or a domain name.
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// The host description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("hostCatalogId")]
        public Input<string>? HostCatalogId { get; set; }

        /// <summary>
        /// The host name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The type of host
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public HostStaticState()
        {
        }
        public static new HostStaticState Empty => new HostStaticState();
    }
}
