// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Boundary
{
    /// <summary>
    /// The role resource allows you to configure a Boundary role.
    /// 
    /// ## Example Usage
    /// 
    /// Basic usage:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Boundary = Pulumi.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.Scope("org", new()
    ///     {
    ///         Name = "organization_one",
    ///         Description = "My first scope!",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var example = new Boundary.Role("example", new()
    ///     {
    ///         Name = "My role",
    ///         Description = "My first role!",
    ///         ScopeId = org.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// Usage with a user resource:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Boundary = Pulumi.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.Scope("org", new()
    ///     {
    ///         Name = "organization_one",
    ///         Description = "My first scope!",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var foo = new Boundary.User("foo", new()
    ///     {
    ///         Name = "User 1",
    ///         ScopeId = org.Id,
    ///     });
    /// 
    ///     var bar = new Boundary.User("bar", new()
    ///     {
    ///         Name = "User 2",
    ///         ScopeId = org.Id,
    ///     });
    /// 
    ///     var example = new Boundary.Role("example", new()
    ///     {
    ///         Name = "My role",
    ///         Description = "My first role!",
    ///         PrincipalIds = new[]
    ///         {
    ///             foo.Id,
    ///             bar.Id,
    ///         },
    ///         ScopeId = org.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// Usage with user and grants resource:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Boundary = Pulumi.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.Scope("org", new()
    ///     {
    ///         Name = "organization_one",
    ///         Description = "My first scope!",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var @readonly = new Boundary.User("readonly", new()
    ///     {
    ///         Name = "readonly",
    ///         Description = "A readonly user",
    ///         ScopeId = org.Id,
    ///     });
    /// 
    ///     var readonlyRole = new Boundary.Role("readonly", new()
    ///     {
    ///         Name = "readonly",
    ///         Description = "A readonly role",
    ///         PrincipalIds = new[]
    ///         {
    ///             @readonly.Id,
    ///         },
    ///         GrantStrings = new[]
    ///         {
    ///             "ids=*;type=*;actions=read",
    ///         },
    ///         ScopeId = org.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// Usage for a project-specific role:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Boundary = Pulumi.Boundary;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var org = new Boundary.Scope("org", new()
    ///     {
    ///         Name = "organization_one",
    ///         Description = "My first scope!",
    ///         ScopeId = "global",
    ///         AutoCreateAdminRole = true,
    ///         AutoCreateDefaultRole = true,
    ///     });
    /// 
    ///     var project = new Boundary.Scope("project", new()
    ///     {
    ///         Name = "project_one",
    ///         Description = "My first scope!",
    ///         ScopeId = org.Id,
    ///         AutoCreateAdminRole = true,
    ///     });
    /// 
    ///     var @readonly = new Boundary.User("readonly", new()
    ///     {
    ///         Name = "readonly",
    ///         Description = "A readonly user",
    ///         ScopeId = org.Id,
    ///     });
    /// 
    ///     var readonlyRole = new Boundary.Role("readonly", new()
    ///     {
    ///         Name = "readonly",
    ///         Description = "A readonly role",
    ///         PrincipalIds = new[]
    ///         {
    ///             @readonly.Id,
    ///         },
    ///         GrantStrings = new[]
    ///         {
    ///             "ids=*;type=*;actions=read",
    ///         },
    ///         ScopeId = project.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    /// $ pulumi import boundary:index/role:Role foo &lt;my-id&gt;
    /// ```
    /// </summary>
    [BoundaryResourceType("boundary:index/role:Role")]
    public partial class Role : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The role description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// A list of scopes for which the grants in this role should apply, which can include the special values "this", "children", or "descendants"
        /// </summary>
        [Output("grantScopeIds")]
        public Output<ImmutableArray<string>> GrantScopeIds { get; private set; } = null!;

        /// <summary>
        /// A list of stringified grants for the role.
        /// </summary>
        [Output("grantStrings")]
        public Output<ImmutableArray<string>> GrantStrings { get; private set; } = null!;

        /// <summary>
        /// The role name. Defaults to the resource name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// A list of principal (user or group) IDs to add as principals on the role.
        /// </summary>
        [Output("principalIds")]
        public Output<ImmutableArray<string>> PrincipalIds { get; private set; } = null!;

        /// <summary>
        /// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
        /// </summary>
        [Output("scopeId")]
        public Output<string> ScopeId { get; private set; } = null!;


        /// <summary>
        /// Create a Role resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Role(string name, RoleArgs args, CustomResourceOptions? options = null)
            : base("boundary:index/role:Role", name, args ?? new RoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Role(string name, Input<string> id, RoleState? state = null, CustomResourceOptions? options = null)
            : base("boundary:index/role:Role", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Role resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Role Get(string name, Input<string> id, RoleState? state = null, CustomResourceOptions? options = null)
        {
            return new Role(name, id, state, options);
        }
    }

    public sealed class RoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The role description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("grantScopeIds")]
        private InputList<string>? _grantScopeIds;

        /// <summary>
        /// A list of scopes for which the grants in this role should apply, which can include the special values "this", "children", or "descendants"
        /// </summary>
        public InputList<string> GrantScopeIds
        {
            get => _grantScopeIds ?? (_grantScopeIds = new InputList<string>());
            set => _grantScopeIds = value;
        }

        [Input("grantStrings")]
        private InputList<string>? _grantStrings;

        /// <summary>
        /// A list of stringified grants for the role.
        /// </summary>
        public InputList<string> GrantStrings
        {
            get => _grantStrings ?? (_grantStrings = new InputList<string>());
            set => _grantStrings = value;
        }

        /// <summary>
        /// The role name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("principalIds")]
        private InputList<string>? _principalIds;

        /// <summary>
        /// A list of principal (user or group) IDs to add as principals on the role.
        /// </summary>
        public InputList<string> PrincipalIds
        {
            get => _principalIds ?? (_principalIds = new InputList<string>());
            set => _principalIds = value;
        }

        /// <summary>
        /// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
        /// </summary>
        [Input("scopeId", required: true)]
        public Input<string> ScopeId { get; set; } = null!;

        public RoleArgs()
        {
        }
        public static new RoleArgs Empty => new RoleArgs();
    }

    public sealed class RoleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The role description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("grantScopeIds")]
        private InputList<string>? _grantScopeIds;

        /// <summary>
        /// A list of scopes for which the grants in this role should apply, which can include the special values "this", "children", or "descendants"
        /// </summary>
        public InputList<string> GrantScopeIds
        {
            get => _grantScopeIds ?? (_grantScopeIds = new InputList<string>());
            set => _grantScopeIds = value;
        }

        [Input("grantStrings")]
        private InputList<string>? _grantStrings;

        /// <summary>
        /// A list of stringified grants for the role.
        /// </summary>
        public InputList<string> GrantStrings
        {
            get => _grantStrings ?? (_grantStrings = new InputList<string>());
            set => _grantStrings = value;
        }

        /// <summary>
        /// The role name. Defaults to the resource name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("principalIds")]
        private InputList<string>? _principalIds;

        /// <summary>
        /// A list of principal (user or group) IDs to add as principals on the role.
        /// </summary>
        public InputList<string> PrincipalIds
        {
            get => _principalIds ?? (_principalIds = new InputList<string>());
            set => _principalIds = value;
        }

        /// <summary>
        /// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
        /// </summary>
        [Input("scopeId")]
        public Input<string>? ScopeId { get; set; }

        public RoleState()
        {
        }
        public static new RoleState Empty => new RoleState();
    }
}
