// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export function getAuthMethod(args: GetAuthMethodArgs, opts?: pulumi.InvokeOptions): Promise<GetAuthMethodResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("boundary:index/getAuthMethod:getAuthMethod", {
        "name": args.name,
        "scopeId": args.scopeId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAuthMethod.
 */
export interface GetAuthMethodArgs {
    name: string;
    scopeId?: string;
}

/**
 * A collection of values returned by getAuthMethod.
 */
export interface GetAuthMethodResult {
    readonly description: string;
    readonly id: string;
    readonly name: string;
    readonly scopeId?: string;
    readonly scopes: outputs.GetAuthMethodScope[];
    readonly type: string;
}
export function getAuthMethodOutput(args: GetAuthMethodOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAuthMethodResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("boundary:index/getAuthMethod:getAuthMethod", {
        "name": args.name,
        "scopeId": args.scopeId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAuthMethod.
 */
export interface GetAuthMethodOutputArgs {
    name: pulumi.Input<string>;
    scopeId?: pulumi.Input<string>;
}
